### ISSUE TITLE
Label localization

### ISSUE THREAD

**Issue by eiswurm** [markocupic/contao-altcha-antispam#3]
What would be the best way to translate the labels? The label texts are inside altcha.min.js and can be overwritten via tags in the form (see https://altcha.org/docs/website-integration). What is the best way to do this in Contao (update-safe)?

Something like this should work:
```html
<form>
  <altcha-widget strings="{"label": "Ich bin ein Mensch","verified": "verifiziert"}"></altcha-widget>
</form>
```

**Comment by markocupic** [comment]
@eiswurm Use the language files to achieve this. see: https://github.com/markocupic/contao-altcha-antispam/blob/793b35a41e9b85a4c28a81c4b6d40656eb2dc5fe/contao/languages/de/default.php#L28
