### ISSUE TITLE
Error: could not find template

### ISSUE THREAD

**Issue by GMTeams** [markocupic/contao-altcha-antispam#4]
Contao 4.13.38
contao-altcha-antispam: 0.4.9 (also on 0.4.8)
PHP 8.1.27

I have no idea what our team would have changed in the Contao installation, but I would not know that there was made an update in the Contao core recently. Nor in the contao-altcha-antispam.

At the time when we had installed contao-altcha-antispam it worked.

And now, when we try to open a frontend page where this form field appears, the following error is thrown:
`request.CRITICAL: Uncaught PHP Exception Exception: "Could not find template "form_altcha_hidden"" at /homepages/19/123/htdocs/_dev/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php line 156 {"exception":"[object] (Exception(code: 0): Could not find template \"form_altcha_hidden\" at /homepages/19/123/htdocs/_dev/contao/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:156)"} []`

**Comment by tuxenberger** [comment]
Contao 4.13.44
contao-altcha-antispam: Version 0.4.9
PHP Version 8.1.28

Same here – after installing the extension and setting up the hmac_key i place the captach field in the form and get this error:

2024-06-06T13:50:03.956998+02:00] request.CRITICAL: Uncaught PHP Exception Exception: "Could not find template "form_altcha_hidden"" at /home/name-of-the-installation/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php line 156 {"exception":"[object] (Exception(code: 0): Could not find template \"form_altcha_hidden\" at /home/name-of-the-installation/vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateLoader.php:156)"} [] 

A quick look in the templates section of the form field says "form_altcha_hidden" is needed. 
Found the template (Twig) in your source - but no html5 template is offered.

Could you give me a hint to fix the problem? Your help is much appreciated to protect our site from spam bots.
