### ISSUE TITLE
config.yaml seems to have no effect - hmac_key

### ISSUE THREAD

**Issue by mbrpf** [markocupic/contao-altcha-antispam#5]
I have put the hmac_key in the config.yaml in the folder config in the main directory.
The form field still has the error/warning that there is no hmac_key.

Did I put the yaml in the wrong folder? Any ideas?

System: Contao 4.13.38 / PHP 8.2.x

**Comment by markocupic** [comment]
@mbrpf You have to put the hmac key in your config/config.yaml

https://github.com/markocupic/contao-altcha-antispam?tab=readme-ov-file#configuration-and-usage

Do not forget to clear and build up the cache afterwards. 

`php composer install`

**Comment by mbrpf** [comment]
Thank you for your fast reply. Doing "composer install" did clear the issue. Have a nice day.
