### ISSUE TITLE
Error at controller

### ISSUE THREAD

**Issue by zonky2** [markocupic/contao-altcha-antispam#9]
Contao 4.13.47, Altcha-AS 0.4.12, PHP 8.2

der Ajax-Aufruf domain.com/_contao_altcha_challenge liefert ein 500er

vendor/markocupic/contao-altcha-antispam/src/Controller/AltchaController.php:25
Too few arguments to function Markocupic\ContaoAltchaAntispam\Controller\AltchaController::__construct(), 0 passed in /html/veramaris-contao/vendor/symfony/http-kernel/Controller/ControllerResolver.php on line 147 and exactly 1 expected

The controller for URI "/_contao_altcha_challenge" is not callable: Controller "Markocupic\ContaoAltchaAntispam\Controller\AltchaController" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?

**Comment by zonky2** [comment]
läuft, wenn man `public: true` setzt
https://github.com/markocupic/contao-altcha-antispam/blob/c3eaa414b99996cc3229cf2c02e981a8af3ede76/config/services.yaml#L5

**Comment by markocupic** [comment]
Fixed in https://github.com/markocupic/contao-altcha-antispam/commit/c3a543cb059255e34e70c202307f16f5c9395d7e

@zonky2 Thank you!
